### PR TITLE
Registration

### PR DESCRIPTION
**Pull request by mikester380**
Added sign up page

### CODE REVIEW

**Comment by Chiagozielam** [comment]
Can you reference back to the design and check for the background color and background images placed there? Is there a reason you didnt add that?

**Comment by Chiagozielam** [comment]
We need to good practice, as such, files you didn't work on shouldn't have changes from you in them, kindle undo your last commit and reverse changes to files you didn't work on

**Comment by iamgideonidoko** [comment]
> We need to good practice, as such, files you didn't work on shouldn't have changes from you in them, kindle undo your last commit and reverse changes to files you didn't work on

@Chiagozielam, I think @mikester380 tried to run a global linting fix that ended up making changes to other files. This is because in your last PR you changed the ESLint config ` without running a global linting fix to make other files follow the new set rules.

**Comment by iamgideonidoko** [comment]
@mikester380 It is not good practice to remove a `precommit` file or any app configuration file. The `precommit` file makes it possible to define scripts to be run before every commit such as the linting check that enforces a standard style guide.

**Comment by iamgideonidoko** [comment]
@mikester380 I've fixed up linting site wide, you shouldn't have issues with other files. I'll close this PR now. Kindly pull updates from `main` to your branch, update accordingly and create another PR.

NB: Avoid styling your components with a generic name like 'button' to avoid styling conflicts. 

Good Job on the components you created. I'll be expecting your PR ASAP!

**Pull request closed without merging**
